Repository heroku/buildpacks-dotnet, pull requests merged in 2025-02, with the labels that each got.

#195 Print the dotnet getting started guide
  .github/workflows/ci.yml
Labels: skip changelog

#194 Restore dotnet tools
  buildpacks/dotnet/CHANGELOG.md
  buildpacks/dotnet/src/detect.rs
  buildpacks/dotnet/src/errors.rs
  buildpacks/dotnet/src/main.rs
  buildpacks/dotnet/tests/dotnet_restore_tools_test.rs
  buildpacks/dotnet/tests/fixtures/console_with_dotnet_tool/.config/dotnet-tools.json
  buildpacks/dotnet/tests/fixtures/console_with_dotnet_tool/Program.cs
  buildpacks/dotnet/tests/fixtures/console_with_dotnet_tool/consoleapp.csproj
  buildpacks/dotnet/tests/fixtures/console_with_dotnet_tool_configuration_error/.config/dotnet-tools.json
  buildpacks/dotnet/tests/fixtures/console_with_dotnet_tool_configuration_error/Program.cs
  buildpacks/dotnet/tests/fixtures/console_with_dotnet_tool_configuration_error/consoleapp.csproj
  buildpacks/dotnet/tests/mod.rs
Labels: enhancement

#202 Fix global json parsing
  buildpacks/dotnet/CHANGELOG.md
  buildpacks/dotnet/src/dotnet/global_json.rs
  buildpacks/dotnet/src/main.rs
  buildpacks/dotnet/tests/fixtures/project_with_nuget_sdk_and_global_json/Test1.cs
  buildpacks/dotnet/tests/fixtures/project_with_nuget_sdk_and_global_json/foo.csproj
  buildpacks/dotnet/tests/fixtures/project_with_nuget_sdk_and_global_json/global.json
  buildpacks/dotnet/tests/sdk_installation_test.rs
Labels: bug

#186 Configure artifacts path to temporary directory
  buildpacks/dotnet/CHANGELOG.md
  buildpacks/dotnet/src/dotnet_publish_command.rs
  buildpacks/dotnet/tests/dotnet_publish_test.rs
Labels: enhancement
