Repository heroku/buildpacks-dotnet, pull requests merged in 2025-03, with the labels that each got.

#208 Adopt global bullet_stream interface
  buildpacks/dotnet/src/layers/nuget_cache.rs
  buildpacks/dotnet/src/layers/sdk.rs
  buildpacks/dotnet/src/main.rs
Labels: skip changelog

#211 Migrate to ureq v3 API
  shared/inventory-updater/src/main.rs
Labels: bug, skip changelog

#212 Skip NuGet package XML doc extraction by default
  buildpacks/dotnet/CHANGELOG.md
  buildpacks/dotnet/src/main.rs
Labels: enhancement

#215 Move VerbosityLevel to dotnet_buildpack_configuration
  buildpacks/dotnet/src/dotnet_buildpack_configuration.rs
  buildpacks/dotnet/src/dotnet_publish_command.rs
Labels: skip changelog

#216 Verify default buildpack configuration
  buildpacks/dotnet/src/dotnet_buildpack_configuration.rs
Labels: skip changelog

#218 Set an explicit PR reviewer for CNB builder release PRs
  .github/workflows/release.yml
Labels: skip changelog

#221 Refactor NuGet layer handling
  buildpacks/dotnet/CHANGELOG.md
  buildpacks/dotnet/src/layers/nuget_cache.rs
  buildpacks/dotnet/src/layers/sdk.rs
  buildpacks/dotnet/src/main.rs
  buildpacks/dotnet/tests/fixtures/testing_buildpack/bin/build
  buildpacks/dotnet/tests/fixtures/testing_buildpack/bin/detect
  buildpacks/dotnet/tests/fixtures/testing_buildpack/buildpack.toml
  buildpacks/dotnet/tests/sdk_installation_test.rs
Labels: skip changelog

#222 Support `test` and `production` execution environments
  buildpacks/dotnet/CHANGELOG.md
  buildpacks/dotnet/src/dotnet_buildpack_configuration.rs
  buildpacks/dotnet/src/errors.rs
  buildpacks/dotnet/src/main.rs
  buildpacks/dotnet/tests/dotnet_publish_test.rs
  buildpacks/dotnet/tests/mod.rs
  buildpacks/dotnet/tests/sdk_installation_test.rs
Labels: enhancement

#229 Pin SHA of third-party GitHub Actions
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/inventory.yml
Labels: skip changelog

#230 Reduce scopes granted to `GITHUB_TOKEN` in GitHub Actions workflows
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
Labels: skip changelog

#225 Refactor artifact resolution
  buildpacks/dotnet/src/main.rs
Labels: skip changelog

#226 Restore .NET tools consistently across environments
  buildpacks/dotnet/CHANGELOG.md
  buildpacks/dotnet/src/main.rs
  buildpacks/dotnet/tests/dotnet_restore_tools_test.rs
  buildpacks/dotnet/tests/fixtures/console_with_dotnet_tool/.config/dotnet-tools.json
  buildpacks/dotnet/tests/fixtures/console_with_dotnet_tool/consoleapp.csproj
  buildpacks/dotnet/tests/sdk_installation_test.rs
Labels: enhancement

#227 Prefer more concise pattern matching
  buildpacks/dotnet/src/main.rs
Labels: skip changelog

#233 Prefer solution file name in test process command
  buildpacks/dotnet/src/main.rs
Labels: skip changelog

#236 Refactor launch process detection
  buildpacks/dotnet/src/launch_process.rs
Labels: skip changelog

#244 Update to Rust 2024 edition
  Cargo.lock
  Cargo.toml
  buildpacks/dotnet/src/detect.rs
  buildpacks/dotnet/src/errors.rs
  buildpacks/dotnet/src/launch_process.rs
  buildpacks/dotnet/src/layers/runtime.rs
  buildpacks/dotnet/src/layers/sdk.rs
  buildpacks/dotnet/src/main.rs
  buildpacks/dotnet/tests/detect_test.rs
  buildpacks/dotnet/tests/dotnet_publish_test.rs
  buildpacks/dotnet/tests/dotnet_restore_tools_test.rs
  buildpacks/dotnet/tests/nuget_layer_test.rs
  buildpacks/dotnet/tests/sdk_installation_test.rs
  buildpacks/dotnet/tests/test_execution_environment_test.rs
  shared/inventory-updater/src/main.rs
Labels: skip changelog

#245 Add cargo-llvm-cov test coverage reports in CI
  .github/workflows/ci.yml
  Cargo.toml
  buildpacks/dotnet/src/main.rs
Labels: skip changelog
